from __future__ import annotations

from datetime import date, time
from decimal import Decimal

from app.extensions import db
from app.models import Market, MarketStatus


def _upsert(model, lookup: dict, values: dict):
    instance = model.query.filter_by(**lookup).first()
    if instance is None:
        instance = model(**lookup)
        db.session.add(instance)
    for key, value in values.items():
        setattr(instance, key, value)
    db.session.flush()
    return instance


EVENTS_2026 = [
    {
        "name": "Clarksville Downtown Market",
        "location_name": "Public Square",
        "address": "1 Public Square",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 6, 20),
        "start_time": time(8, 0),
        "end_time": time(12, 0),
        "booth_fee": Decimal("50.00"),
        "application_fee": Decimal("10.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "Voted #1 Farmers Market in TN. Weekly Saturday market through Oct 3. Great foot traffic for handmade items, dragons, and fidgets.",
    },
    {
        "name": "Sango Night Market",
        "location_name": "Real Life Sango Church",
        "address": "731 Highway 76",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 6, 22),
        "start_time": time(16, 0),
        "end_time": time(19, 0),
        "booth_fee": Decimal("25.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Medium",
        "notes": "Weekly Monday night market. Baked goods, crafts, vegetables. Runs through Nov 11. Evening market good for after-work crowd.",
    },
    {
        "name": "Thursday Night Market at Old Glory",
        "location_name": "Old Glory Distilling Co.",
        "address": "451 Alfred Thun Road",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 6, 25),
        "start_time": time(17, 0),
        "end_time": time(20, 0),
        "booth_fee": Decimal("35.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Medium",
        "notes": "Weekly Thursday market with live music, craft vendors, bakers. Family-friendly with distillery amenities. Runs through Nov 6.",
    },
    {
        "name": "Clarksville Downtown Market",
        "location_name": "Public Square",
        "address": "1 Public Square",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 6, 27),
        "start_time": time(8, 0),
        "end_time": time(12, 0),
        "booth_fee": Decimal("50.00"),
        "application_fee": Decimal("10.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "Peak summer season at the downtown market. Good for flexi animals, keychains, and fidgets.",
    },
    {
        "name": "Nashville Flea Market - June",
        "location_name": "Nashville Fairgrounds",
        "address": "500 Wedgewood Avenue",
        "city": "Nashville",
        "state": "TN",
        "event_date": date(2026, 6, 26),
        "start_time": time(9, 0),
        "end_time": time(17, 0),
        "booth_fee": Decimal("85.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "High",
        "notes": "Large flea market with crafts, antiques, and food. Multi-day event (Jun 26-28). Good for market research and bulk sales.",
    },
    {
        "name": "Sunday on Strawberry",
        "location_name": "Strawberry Alley",
        "address": "Strawberry Alley",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 7, 5),
        "start_time": time(10, 0),
        "end_time": time(14, 0),
        "booth_fee": Decimal("30.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Medium",
        "notes": "Monthly Sunday market on 1st Sunday. Small businesses and crafty sellers. Runs April through November.",
    },
    {
        "name": "Clarksville Downtown Market",
        "location_name": "Public Square",
        "address": "1 Public Square",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 7, 11),
        "start_time": time(8, 0),
        "end_time": time(12, 0),
        "booth_fee": Decimal("50.00"),
        "application_fee": Decimal("10.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "Mid-summer market. Good test for Clarksville/Tennessee-themed items as tourist season peaks.",
    },
    {
        "name": "Tomato Art Fest",
        "location_name": "Five Points",
        "address": "Five Points, East Nashville",
        "city": "Nashville",
        "state": "TN",
        "event_date": date(2026, 8, 7),
        "start_time": time(17, 0),
        "end_time": time(21, 0),
        "booth_fee": Decimal("150.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "Popular arts festival with crafts, fine art, food, and live music. Large crowds, family-friendly. Aug 7-8. Great fit for custom and personalized items.",
    },
    {
        "name": "Clarksville Downtown Market",
        "location_name": "Public Square",
        "address": "1 Public Square",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 8, 22),
        "start_time": time(8, 0),
        "end_time": time(12, 0),
        "booth_fee": Decimal("50.00"),
        "application_fee": Decimal("10.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "Late summer market. Good for back-to-school items and small business products.",
    },
    {
        "name": "Sunday on Strawberry",
        "location_name": "Strawberry Alley",
        "address": "Strawberry Alley",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 9, 6),
        "start_time": time(10, 0),
        "end_time": time(14, 0),
        "booth_fee": Decimal("30.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Medium",
        "notes": "September edition of the monthly Sunday market.",
    },
    {
        "name": "Grails & Glory Vendor Event",
        "location_name": "Wilma Rudolph Event Center",
        "address": "1190 Cumberland Drive",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 9, 6),
        "start_time": time(10, 0),
        "end_time": time(17, 0),
        "booth_fee": Decimal("75.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "High",
        "notes": "Indoor vendor market at the Wilma Rudolph Event Center. Multiple categories including crafts and handmade goods.",
    },
    {
        "name": "Clarksville Craft Festival by Handmade Nashville",
        "location_name": "Madison Street United Methodist Church",
        "address": "319 Madison Street",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 9, 13),
        "start_time": time(9, 0),
        "end_time": time(16, 0),
        "booth_fee": Decimal("65.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "High",
        "notes": "Handmade Nashville craft festival. Excellent fit for 3D printed gifts, dragons, flexi animals, and personalized items. Juried craft event.",
    },
    {
        "name": "Clarksville Downtown Market",
        "location_name": "Public Square",
        "address": "1 Public Square",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 9, 19),
        "start_time": time(8, 0),
        "end_time": time(12, 0),
        "booth_fee": Decimal("50.00"),
        "application_fee": Decimal("10.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "Fall season at the downtown market. Cooler weather means better foot traffic.",
    },
    {
        "name": "Riverfront Jerk Festival 2026",
        "location_name": "Kenwood High School",
        "address": "3945 Kenwood Drive",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 9, 26),
        "start_time": time(13, 0),
        "end_time": time(20, 0),
        "booth_fee": Decimal("100.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "High",
        "notes": "Community festival with crafts, food, and live music. Large diverse crowd. Good exposure for the brand.",
    },
    {
        "name": "Nashville Flea Market - September",
        "location_name": "Nashville Fairgrounds",
        "address": "500 Wedgewood Avenue",
        "city": "Nashville",
        "state": "TN",
        "event_date": date(2026, 9, 25),
        "start_time": time(9, 0),
        "end_time": time(17, 0),
        "booth_fee": Decimal("85.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "High",
        "notes": "Large monthly flea market. Sep 25-27. Good for selling surplus inventory and market testing new products.",
    },
    {
        "name": "Artsville Fest 2026",
        "location_name": "Downtown Commons",
        "address": "215 Legion Street",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 10, 3),
        "start_time": time(10, 0),
        "end_time": time(16, 0),
        "booth_fee": Decimal("75.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "Major downtown arts festival with chalk walk, live muralists, 50+ vendors, kid zone. Benefit for ArtLink Clarksville. Thousands of attendees. EXCELLENT FIT.",
    },
    {
        "name": "Clarksville Downtown Market - Final Day",
        "location_name": "Public Square",
        "address": "1 Public Square",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 10, 3),
        "start_time": time(8, 0),
        "end_time": time(12, 0),
        "booth_fee": Decimal("50.00"),
        "application_fee": Decimal("10.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "Last Downtown Market of the season. End-of-season sales and community farewell.",
    },
    {
        "name": "Fall Tennessee Craft Fair",
        "location_name": "Centennial Park",
        "address": "2500 West End Avenue",
        "city": "Nashville",
        "state": "TN",
        "event_date": date(2026, 10, 9),
        "start_time": time(10, 0),
        "end_time": time(18, 0),
        "booth_fee": Decimal("250.00"),
        "application_fee": Decimal("35.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "48th Annual juried craft fair. Ranked top 25 in the US. 45,000+ visitors. Oct 9-11. Premium event for handmade crafts. Expensive but excellent exposure.",
    },
    {
        "name": "Clarksville Oktoberfest",
        "location_name": "Beachaven Vineyards & Winery",
        "address": "1100 Dunlop Lane",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 10, 10),
        "start_time": time(11, 0),
        "end_time": time(19, 0),
        "booth_fee": Decimal("100.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "High",
        "notes": "Family-friendly Oktoberfest with German food, live music, and craft vendors. Oct 10-13. Good for market impulse items and custom gifts.",
    },
    {
        "name": "Grails & Glory Vendor Event - November",
        "location_name": "Wilma Rudolph Event Center",
        "address": "1190 Cumberland Drive",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 11, 21),
        "start_time": time(10, 0),
        "end_time": time(17, 0),
        "booth_fee": Decimal("75.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "High",
        "notes": "Holiday season vendor event. Nov 21-22. Good for Christmas gift items, dragons, personalized gifts.",
    },
    {
        "name": "11th Annual Handmade Nashville Holiday Market",
        "location_name": "Red Caboose Park",
        "address": "1110 Knob Road",
        "city": "Nashville",
        "state": "TN",
        "event_date": date(2026, 11, 28),
        "start_time": time(10, 0),
        "end_time": time(16, 0),
        "booth_fee": Decimal("125.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "Holiday market on Small Business Saturday. Great for holiday shoppers looking for unique handmade gifts. Excellent fit for personalized items and ornaments.",
    },
    {
        "name": "Clarksville Christmas Market",
        "location_name": "Rossview Road Pavilion",
        "address": "1921 Rossview Road",
        "city": "Clarksville",
        "state": "TN",
        "event_date": date(2026, 11, 28),
        "start_time": time(14, 0),
        "end_time": time(18, 0),
        "booth_fee": Decimal("65.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "120+ local vendors, Santa photos, family-friendly. Free admission. Nov 28-29. Coordinates with Small Business Saturday. EXCELLENT FIT for holiday 3D printed gifts.",
    },
    {
        "name": "Nashvillage Holiday Market",
        "location_name": "Walk of Fame Park",
        "address": "141 5th Avenue South",
        "city": "Nashville",
        "state": "TN",
        "event_date": date(2026, 12, 4),
        "start_time": time(16, 0),
        "end_time": time(21, 0),
        "booth_fee": Decimal("200.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "Very High",
        "notes": "Premium holiday market in downtown Nashville. Runs Dec 3-6 and Dec 10-13. High foot traffic from holiday shoppers and tourists. Great for Tennessee-themed items.",
    },
    {
        "name": "Nashville Flea Market - December",
        "location_name": "Nashville Fairgrounds",
        "address": "500 Wedgewood Avenue",
        "city": "Nashville",
        "state": "TN",
        "event_date": date(2026, 12, 18),
        "start_time": time(9, 0),
        "end_time": time(17, 0),
        "booth_fee": Decimal("85.00"),
        "status": MarketStatus.INTERESTED,
        "expected_traffic": "High",
        "notes": "Last-minute holiday shopping crowd. Dec 18-20. Good for clearing holiday inventory and end-of-year sales.",
    },
]

CLARKSVILLE_RECURRING_NOTES = {
    "downtown_market": (
        "The Clarksville Downtown Market runs every Saturday from May 9 to October 3, "
        "8am-12pm at Public Square. Voted #1 Farmers Market in Tennessee. "
        "Booth fee ~$50-60/ Saturday. Applications open in spring."
    ),
    "sango_night_market": (
        "The Sango Night Market runs every Monday from May 26 to November 11, "
        "4-7pm at Real Life Sango Church (731 Highway 76). "
        "Booth fee ~$25. Evening market, good for after-work crowds."
    ),
    "old_glory_market": (
        "Thursday Night Market at Old Glory Distilling runs every Thursday from May 8 to November 6, "
        "5-8pm. Booth fee ~$35. Live music, family-friendly."
    ),
    "sunday_strawberry": (
        "Sunday on Strawberry runs on the 1st Sunday of each month, April through November, "
        "10am-2pm on Strawberry Alley. Booth fee ~$30."
    ),
    "nashville_flea": (
        "Nashville Flea Market runs the last full weekend of each month (Fri-Sun) "
        "at Nashville Fairgrounds. Booth fee ~$85. 50+ food vendors."
    ),
}


def seed_events_2026() -> dict:
    counts = {"events": 0}
    for event_data in EVENTS_2026:
        status = event_data.pop("status", MarketStatus.INTERESTED)
        _upsert(
            Market,
            {"name": event_data["name"], "event_date": event_data["event_date"]},
            {**event_data, "status": status},
        )
        counts["events"] += 1

    db.session.commit()
    return counts
