from __future__ import annotations

from decimal import Decimal

from app.services.model_analysis import slice_with_prusaslicer
from app.services import slicer_client


class _FakeSlicerClient:
    def is_configured(self) -> bool:
        return True

    def slice(self, **kwargs):
        return {
            "success": True,
            "filament_grams": "12.5",
            "print_minutes": "42",
            "stats": {"profile_used": kwargs.get("profile_name")},
            "gcode": "; generated by fake slicer\n",
        }


def test_slice_with_microservice_writes_returned_gcode_to_requested_output(tmp_path, monkeypatch):
    model_path = tmp_path / "model.stl"
    output_path = tmp_path / "quote.gcode"
    model_path.write_text("solid model\nendsolid model\n", encoding="utf-8")
    monkeypatch.setattr(slicer_client, "get_slicer_client", lambda: _FakeSlicerClient())

    result = slice_with_prusaslicer(
        model_path,
        profile_name="bambu_a1.ini",
        output_path=output_path,
        slicer_options={"infill_percent": "20%"},
    )

    assert result.success is True
    assert result.filament_grams == Decimal("12.5")
    assert result.print_minutes == Decimal("42")
    assert output_path.read_text(encoding="utf-8") == "; generated by fake slicer\n"
