"""Add receipt management tables

Revision ID: 0e8b440db6b9
Revises: 70f89a7a850b
Create Date: 2026-06-16 21:14:49.491216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8b440db6b9'
down_revision = '70f89a7a850b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('receipts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PREPROCESSING', 'OCR_PROCESSING', 'AI_EXTRACTING', 'NEEDS_REVIEW', 'POSSIBLE_DUPLICATE', 'APPROVED', 'REJECTED', 'ARCHIVED', 'PROCESSING_FAILED', name='receiptstatus', native_enum=False, length=40), nullable=False),
    sa.Column('original_file_id', sa.String(length=255), nullable=True),
    sa.Column('preview_file_id', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_file_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.Enum('UPLOAD', 'CAMERA', 'EMAIL_IMPORT', 'MANUAL', name='receiptsourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('raw_ocr_json', sa.Text(), nullable=True),
    sa.Column('ai_extracted_json', sa.Text(), nullable=True),
    sa.Column('final_reviewed_json', sa.Text(), nullable=True),
    sa.Column('parser_provider', sa.String(length=80), nullable=True),
    sa.Column('parser_model', sa.String(length=80), nullable=True),
    sa.Column('parser_version', sa.String(length=40), nullable=True),
    sa.Column('confidence_overall', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('low_confidence_flags', sa.Text(), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('merchant_normalized_id', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('store_number', sa.String(length=40), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('receipt_number', sa.String(length=80), nullable=True),
    sa.Column('transaction_number', sa.String(length=80), nullable=True),
    sa.Column('register_number', sa.String(length=40), nullable=True),
    sa.Column('cashier_name_or_id', sa.String(length=80), nullable=True),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=40), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tip_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deposit_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rounding_adjustment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=60), nullable=True),
    sa.Column('payment_card_brand', sa.String(length=40), nullable=True),
    sa.Column('payment_card_last4', sa.String(length=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duplicate_group_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_date_time'), 'receipts', ['date_time'], unique=False)
    op.create_index(op.f('ix_receipts_duplicate_group_id'), 'receipts', ['duplicate_group_id'], unique=False)
    op.create_index(op.f('ix_receipts_file_hash'), 'receipts', ['file_hash'], unique=False)
    op.create_index(op.f('ix_receipts_grand_total'), 'receipts', ['grand_total'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=False)
    op.create_index(op.f('ix_receipts_status'), 'receipts', ['status'], unique=False)
    op.create_index(op.f('ix_receipts_user_id'), 'receipts', ['user_id'], unique=False)
    op.create_table('receipt_adjustment_allocations',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('TAX', 'FEE', 'DISCOUNT', 'DEPOSIT', 'TIP', 'ROUNDING', name='adjustmenttype', native_enum=False, length=40), nullable=False),
    sa.Column('allocation_method', sa.Enum('EXACT', 'TAXABLE_PROPORTIONAL', 'SUBTOTAL_PROPORTIONAL', 'CATEGORY_RULE', 'MANUAL', 'UNALLOCATED', name='allocationmethod', native_enum=False, length=40), nullable=False),
    sa.Column('source_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unallocated_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('calculation_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_adjustment_allocations_receipt_id'), 'receipt_adjustment_allocations', ['receipt_id'], unique=False)
    op.create_table('receipt_audit_events',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_audit_events_action'), 'receipt_audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_receipt_audit_events_receipt_id'), 'receipt_audit_events', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_receipt_audit_events_user_id'), 'receipt_audit_events', ['user_id'], unique=False)
    op.create_table('receipt_line_items',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('normalized_description', sa.String(length=500), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('upc', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_tip_allocation', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxable_status', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('confidence_description', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence_price', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence_quantity', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence_tax', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('is_inventory_candidate', sa.Boolean(), nullable=False),
    sa.Column('is_personal_or_excluded', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_line_items_receipt_id'), 'receipt_line_items', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_receipt_line_items_sku'), 'receipt_line_items', ['sku'], unique=False)
    op.create_table('receipt_line_allocations',
    sa.Column('receipt_line_item_id', sa.Integer(), nullable=False),
    sa.Column('allocation_type', sa.Enum('MARKET', 'CUSTOM_JOB', 'INVENTORY', 'GENERAL_EXPENSE', 'PERSONAL_EXCLUDED', name='allocationtype', native_enum=False, length=40), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('custom_job_id', sa.Integer(), nullable=True),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('expense_category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quantity_allocated', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receipt_line_item_id'], ['receipt_line_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_line_allocations_custom_job_id'), 'receipt_line_allocations', ['custom_job_id'], unique=False)
    op.create_index(op.f('ix_receipt_line_allocations_inventory_item_id'), 'receipt_line_allocations', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_receipt_line_allocations_market_id'), 'receipt_line_allocations', ['market_id'], unique=False)
    op.create_index(op.f('ix_receipt_line_allocations_receipt_line_item_id'), 'receipt_line_allocations', ['receipt_line_item_id'], unique=False)
    op.add_column('expenses', sa.Column('receipt_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_receipt_id'), 'expenses', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_receipt_id'), table_name='expenses')
    op.drop_column('expenses', 'receipt_id')
    op.drop_index(op.f('ix_receipt_line_allocations_receipt_line_item_id'), table_name='receipt_line_allocations')
    op.drop_index(op.f('ix_receipt_line_allocations_market_id'), table_name='receipt_line_allocations')
    op.drop_index(op.f('ix_receipt_line_allocations_inventory_item_id'), table_name='receipt_line_allocations')
    op.drop_index(op.f('ix_receipt_line_allocations_custom_job_id'), table_name='receipt_line_allocations')
    op.drop_table('receipt_line_allocations')
    op.drop_index(op.f('ix_receipt_line_items_sku'), table_name='receipt_line_items')
    op.drop_index(op.f('ix_receipt_line_items_receipt_id'), table_name='receipt_line_items')
    op.drop_table('receipt_line_items')
    op.drop_index(op.f('ix_receipt_audit_events_user_id'), table_name='receipt_audit_events')
    op.drop_index(op.f('ix_receipt_audit_events_receipt_id'), table_name='receipt_audit_events')
    op.drop_index(op.f('ix_receipt_audit_events_action'), table_name='receipt_audit_events')
    op.drop_table('receipt_audit_events')
    op.drop_index(op.f('ix_receipt_adjustment_allocations_receipt_id'), table_name='receipt_adjustment_allocations')
    op.drop_table('receipt_adjustment_allocations')
    op.drop_index(op.f('ix_receipts_user_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_status'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_grand_total'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_file_hash'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_duplicate_group_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_date_time'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
