"""Add markets and expenses

Revision ID: 83911c79966b
Revises: 9c37ed157845
Create Date: 2026-06-14 21:37:35.035099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83911c79966b'
down_revision = '9c37ed157845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('FILAMENT', 'PRINTER_PARTS', 'TOOLS', 'BOOTH_FEES', 'PACKAGING', 'SHIPPING', 'SOFTWARE', 'ADVERTISING', 'VEHICLE_TRAVEL', 'OFFICE_SUPPLIES', 'LICENSES_FEES', 'OTHER', name='expensecategory', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('related_market_id', sa.Integer(), nullable=True),
    sa.Column('related_order_id', sa.Integer(), nullable=True),
    sa.Column('receipt_file_path', sa.String(length=300), nullable=True),
    sa.Column('tax_deductible', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_related_market_id'), 'expenses', ['related_market_id'], unique=False)
    op.create_index(op.f('ix_expenses_related_order_id'), 'expenses', ['related_order_id'], unique=False)
    op.create_table('markets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('booth_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('application_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('INTERESTED', 'APPLIED', 'ACCEPTED', 'WAITLISTED', 'REJECTED', 'SCHEDULED', 'COMPLETED', 'CANCELED', 'NOT_WORTH_REPEATING', 'REPEAT', name='marketstatus', native_enum=False, length=40), nullable=False),
    sa.Column('expected_traffic', sa.String(length=100), nullable=True),
    sa.Column('actual_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_event_date'), 'markets', ['event_date'], unique=False)
    op.create_index(op.f('ix_markets_name'), 'markets', ['name'], unique=False)
    op.create_index(op.f('ix_markets_status'), 'markets', ['status'], unique=False)
    op.create_table('market_packing_lists',
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('planned_quantity', sa.Integer(), nullable=True),
    sa.Column('packed_quantity', sa.Integer(), nullable=True),
    sa.Column('sold_quantity', sa.Integer(), nullable=True),
    sa.Column('returned_quantity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_packing_lists_market_id'), 'market_packing_lists', ['market_id'], unique=False)
    op.create_index(op.f('ix_market_packing_lists_product_id'), 'market_packing_lists', ['product_id'], unique=False)
    op.create_index(op.f('ix_market_packing_lists_variant_id'), 'market_packing_lists', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_packing_lists_variant_id'), table_name='market_packing_lists')
    op.drop_index(op.f('ix_market_packing_lists_product_id'), table_name='market_packing_lists')
    op.drop_index(op.f('ix_market_packing_lists_market_id'), table_name='market_packing_lists')
    op.drop_table('market_packing_lists')
    op.drop_index(op.f('ix_markets_status'), table_name='markets')
    op.drop_index(op.f('ix_markets_name'), table_name='markets')
    op.drop_index(op.f('ix_markets_event_date'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_expenses_related_order_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_related_market_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
