"""add theme_slug to users

Revision ID: 9c37ed157845
Revises: b0a088770391
Create Date: 2026-06-14 20:37:42.198832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c37ed157845'
down_revision = 'b0a088770391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme_slug', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme_slug')
    # ### end Alembic commands ###
