#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${AUDIT_POSTGRES_DB};
    CREATE USER ${AUDIT_POSTGRES_USER} WITH PASSWORD '${AUDIT_POSTGRES_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${AUDIT_POSTGRES_DB} TO ${AUDIT_POSTGRES_USER};
    ALTER DATABASE ${AUDIT_POSTGRES_DB} OWNER TO ${AUDIT_POSTGRES_USER};

    CREATE DATABASE ${INTELLIGENCE_POSTGRES_DB};
    CREATE USER ${INTELLIGENCE_POSTGRES_USER} WITH PASSWORD '${INTELLIGENCE_POSTGRES_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${INTELLIGENCE_POSTGRES_DB} TO ${INTELLIGENCE_POSTGRES_USER};
    ALTER DATABASE ${INTELLIGENCE_POSTGRES_DB} OWNER TO ${INTELLIGENCE_POSTGRES_USER};

    CREATE DATABASE ${TREND_SCOUT_POSTGRES_DB};
    CREATE USER ${TREND_SCOUT_POSTGRES_USER} WITH PASSWORD '${TREND_SCOUT_POSTGRES_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${TREND_SCOUT_POSTGRES_DB} TO ${TREND_SCOUT_POSTGRES_USER};
    ALTER DATABASE ${TREND_SCOUT_POSTGRES_DB} OWNER TO ${TREND_SCOUT_POSTGRES_USER};

    CREATE DATABASE dfpos_test;
    GRANT ALL PRIVILEGES ON DATABASE dfpos_test TO ${POSTGRES_USER};
EOSQL

# Allow LAN clients (192.168.0.0/16) to authenticate with the
# SCRAM-SHA-256 password stored in pg_authid. Only affects fresh
# database initialisation; for existing databases, edit
# /var/lib/postgresql/data/pg_hba.conf directly (or recreate the
# data volume).
{
    echo ""
    echo "# LAN clients (added by docker/postgres/init)"
    echo "host    all             all             192.168.0.0/16         scram-sha-256"
} >> /var/lib/postgresql/data/pg_hba.conf
