#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${AUDIT_POSTGRES_DB};
    CREATE USER ${AUDIT_POSTGRES_USER} WITH PASSWORD '${AUDIT_POSTGRES_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${AUDIT_POSTGRES_DB} TO ${AUDIT_POSTGRES_USER};
    ALTER DATABASE ${AUDIT_POSTGRES_DB} OWNER TO ${AUDIT_POSTGRES_USER};

    CREATE DATABASE ${INTELLIGENCE_POSTGRES_DB};
    CREATE USER ${INTELLIGENCE_POSTGRES_USER} WITH PASSWORD '${INTELLIGENCE_POSTGRES_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${INTELLIGENCE_POSTGRES_DB} TO ${INTELLIGENCE_POSTGRES_USER};
    ALTER DATABASE ${INTELLIGENCE_POSTGRES_DB} OWNER TO ${INTELLIGENCE_POSTGRES_USER};

    CREATE DATABASE dfpos_test;
    GRANT ALL PRIVILEGES ON DATABASE dfpos_test TO ${POSTGRES_USER};
EOSQL
